Only install 'parallel' package when necessary
It is not necessary when the --iso or --repository option is used.

It is possible that this could fix the issue at #30. The reason is
that if 'parallel' fails to install, the variable TLREPO is set to a
default value. So in the code if there is a check that assumes that
a non-empty TLREPO variable means an ISO is not being used, then
this would explain #30.

However, I'm guessing there are additional problems in #30.

diff --git a/install-tl-ubuntu b/install-tl-ubuntu
--- a/install-tl-ubuntu
+++ b/install-tl-ubuntu
@@ -387,10 +387,18 @@ checkEnvVars
 
 if [ "${NO_APT_DPKG}" != "1" ]; then
     echo "${ECHOPREFIX}running apt and dpkg commands..."
-    # 'parallel' for the automatic repo detection
-    PARPREREQ='parallel'
-    apt-get -y install --no-install-recommends ${PARPREREQ} >&3 2>&1 \
-        || { echo "${ECHOPREFIX}apt-get cannot install ${PARPREREQ} package to look for fastest mirror so we will use the default TeX Live repository."; TLREPO='http://mirror.utexas.edu/ctan/'; }
+
+    if [ -z "${TLREPO:-}" -a -z "${ISO_FILE}" ]; then
+      # parallel is currently only used for repo detection, so is not needed
+      # with an ISO or with a specified directory.
+      # If I do use parallel for something else, then make sure that TLREPO is
+      # only set when appropriate (e.g. not if --iso option is used).
+      PARPREREQ='parallel' apt-get -y install --no-install-recommends
+      ${PARPREREQ} >&3 2>&1 \ || { echo "${ECHOPREFIX}apt-get cannot install
+      ${PARPREREQ} package to look for fastest mirror so we will use the
+      default TeX Live repository."; TLREPO='http://mirror.utexas.edu/ctan/'; }
+    fi
+
     # libfile-fcntllock-perl because otherwise equivs gives:
     #     "File::FcntlLock not available; using flock which is not NFS-safejo"
     # gcc because otherwise:
