Make script runnable as a stand-alone (fixes #3)
The file debian-control-texlive-in will now be downloaded
if it is not in the directory from which install-tl-ubuntu is run.
It is the only dependency and thus now only install-tl-ubuntu is
needed for things to work. I've learned that many people use Github
by downloading files individually. This commit makes it so they only
need to download one file.

An alternative would be to embed the control file in the main script,
but this would remove the flexibility of modifying the control file
while updating to the latest install-tl-ubuntu. One such use case is
that one might want to modify the Debian control file so that Ubuntu
installs a certain (older) version of a package. This should then
probably (unless you want both versions) be accompanied by a change
in the TeX Live profile (use --profile and see example.profile).

diff --git a/install-tl-ubuntu b/install-tl-ubuntu
--- a/install-tl-ubuntu
+++ b/install-tl-ubuntu
@@ -358,15 +358,15 @@ exec 3>> "${LOG_DIR}/install-tl-ubuntu_EXTRAS.log"
 # For some, we just report to STDERR (warnings).
 MAINRET=0
 
-# TODO
-## ALTERNATIVE if this is the only file dependency, we could dl it or put inside this script.
-requiredFiles=(
-    debian-control-texlive-in.txt
-)
-for file in "${requiredFiles[@]}"; do
-        [ -e "${file}" ] \
-    || { echo "${ERRORPREFIX}required file, ${file}, does not exist." >&2; clean_error; }
-done
+## ALTERNATIVE we could embed it.
+if [ ! -e "debian-control-texlive-in.txt" ]; then
+    echo "${ECHOPREFIX}downloading the Debian control file..."
+    ${WGET_CMD} "https://raw.github.com/scottkosty/install-tl-ubuntu/master/debian-control-texlive-in.txt"
+    if [ "$?" != "0" ]; then
+        echo "${ERRORPREFIX}failed to download the necessary file, debian-control-texlive-in.txt." >&2
+        clean_error
+    fi
+fi
 
 # Check to see if TeX Live environment variables are set (which might cause conflicts)
 checkEnvVars
