Options --repository and --iso are incompatible
Give error and exit if both are used.

diff --git a/install-tl-ubuntu b/install-tl-ubuntu
--- a/install-tl-ubuntu
+++ b/install-tl-ubuntu
@@ -259,6 +259,11 @@ if [ "${HELP}" = "1" ]; then
   exit 0
 fi
 
+if [ "${ISO_FILE}" != "" -a -n "${TLREPO:-}" ]; then
+    echo "${ERRORPREFIX}the options --repository and --iso are incompatible" >&2
+    clean_error
+fi
+
 ### /begin function declarations
 
 function checkEnvVars ()
