--hebrew: install culmus after ivritex
For some reason, first installing ivritex and then removing it and
installing culmus leads to fixed compilation (of LyX documents).

diff --git a/install-tl-ubuntu b/install-tl-ubuntu
--- a/install-tl-ubuntu
+++ b/install-tl-ubuntu
@@ -836,22 +836,29 @@ if [ "${HEBREW}" = 1 ]; then
       mkdir "/tmp/HebrewFonts" &&
       cd "/tmp/HebrewFonts" &&
       # install-tl-ubuntu used to install the ivritex deb. Instead, we now install culmus directly.
-      #${WGET_CMD} "http://archive.debian.org/debian/pool/main/i/ivritex/ivritex_1.1.1-6_all.deb" &&
-      #ar x "ivritex_1.1.1-6_all.deb" && tar -xf "data.tar.gz" &&
-      #rsync -a "usr/share/texmf/" "${dTEXMFLOCAL}"
-      ${WGET_CMD} -O culmus-latex-0.7-r1.tar.gz "https://sourceforge.net/projects/ivritex/files/culmus-latex/culmus-latex-0.7/culmus-latex-0.7-r1.tar.gz/download" &&
-      tar -xvzf culmus-latex-0.7-r1.tar.gz &&
-      cd culmus-latex-0.7-r1 &&
-      sudo mkdir -p "${dTEXMFLOCAL}" &&
-      sudo rsync -a "usr/share/texmf/fonts" "${dTEXMFLOCAL}/"
+      ${WGET_CMD} "http://archive.debian.org/debian/pool/main/i/ivritex/ivritex_1.1.1-6_all.deb" &&
+      ar x "ivritex_1.1.1-6_all.deb" && tar -xf "data.tar.gz" &&
+      rsync -a "usr/share/texmf/" "${dTEXMFLOCAL}"
     ) >&3 2>&1 \
     || { echo "${WARNINGPREFIX}Hebrew font was not installed correctly." >&2; MAINRET=1; }
 fi
 
 echo "${ECHOPREFIX}running texhash..."
 texhash >&3 2>&1 && echo "${ECHOPREFIX}texhash was successful." || { echo "${WARNINGPREFIX}texhash exited with error." >&2; MAINRET=1; }
+
 if [ "${HEBREW}" = 1 ]; then
-  updmap-sys --enable Map=culmus.map || { echo "${WARNINGPREFIX}updmap-sys exited with error (--hebrew)." >&2; MAINRET=1; }
+  # remove ivritex:
+  sudo rm -rf /usr/local/texlive/texmf-local/tex/generic/ivritex &&
+  sudo rm -rf /usr/local/texlive/texmf-local/bibtex/ivritex &&
+  mkdir "/tmp/HebrewFonts2" &&
+  cd "/tmp/HebrewFonts2" &&
+  ${WGET_CMD} -O culmus-latex-0.7-r1.tar.gz "https://sourceforge.net/projects/ivritex/files/culmus-latex/culmus-latex-0.7/culmus-latex-0.7-r1.tar.gz/download" &&
+  tar -xvzf culmus-latex-0.7-r1.tar.gz &&
+  cd culmus-latex-0.7-r1 &&
+  mkdir -p "${dTEXMFLOCAL}" &&
+  rsync -a "usr/share/texmf/fonts" "${dTEXMFLOCAL}/"
+  /opt/texbin/mktexlsr &&
+  /opt/texbin/updmap-sys --enable Map=culmus.map || { echo "${WARNINGPREFIX}updmap-sys exited with error (--hebrew)." >&2; MAINRET=1; }
 fi
 
 
