No auto repo if no 'parallel' package (fixes #9)
The 'parallel' package in Ubuntu 12.04 is only available
through a PPA which I do not want to force on the user.

Thanks to Mark Rijckenberg for reporting this.

diff --git a/install-tl-ubuntu b/install-tl-ubuntu
--- a/install-tl-ubuntu
+++ b/install-tl-ubuntu
@@ -327,7 +327,7 @@ function checkEnvVars ()
 ### /end function declarations
 
 if [ "${VERSION}" = "1" ]; then
-  echo -e "\\ninstall-tl-ubuntu\\nVersion 0.4\\nAuthor: Scott Kostyshak\\nContact: skostysh@princeton.edu"
+  echo -e "\\ninstall-tl-ubuntu\\nVersion 0.4.1\\nAuthor: Scott Kostyshak\\nContact: skostysh@princeton.edu"
   exit 0
 fi
 
@@ -381,7 +381,10 @@ if [ "${NO_APT_DPKG}" != "1" ]; then
     # gcc because otherwise:
     #     "Couldn't determine gcc system type, falling back to default (native compilation)"
     # 'parallel' for the automatic repo detection
-    PREREQS='libfile-fcntllock-perl gcc equivs libwww-perl fontconfig unzip parallel'
+    PARPREREQ='parallel'
+    apt-get -y install --no-install-recommends ${PARPREREQ} >&3 2>&1 \
+        || { echo "${ECHOPREFIX}apt-get cannot install ${PARPREREQ} package to look for fastest mirror so we will use the default TeX Live repository."; TLREPO='http://mirror.utexas.edu/ctan/'; }
+    PREREQS='libfile-fcntllock-perl gcc equivs libwww-perl fontconfig unzip'
     apt-get -y install --no-install-recommends ${PREREQS} >&3 2>&1 \
         || { echo "${ERRORPREFIX}apt-get failed to install ${PREREQS} in $0" >&2; clean_error; }
     # TODO put the -out.txt in a temp dir, or in the log file.
